# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            Washington Merged Longitudinal Administrative Data
tagline:          ''
description:      'A data resource of Washingtonians for Washingtonians' 
url:              "https://j-romich.github.io"
baseurl:          "/wmlad"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/j-romich/wmlad/
